// Generated by CoffeeScript 1.9.3
(function() {
  var Task;

  Task = (function() {
    function Task() {}

    Task.prototype.name = 'test';

    return Task;

  })();

  describe('Task instance', function() {
    it('should not fail', function() {
      return jQuery(document).ready(function() {
        app.model.Src = new Maslosoft.Ko.BalinDev.Models.Src({
          filename: './images/maslosoft.png'
        });
        return ko.applyBindings({
          model: app.model
        });
      });
    });
    return it('should have name', function() {
      var task;
      task = new Task;
      return task.name.should.equal("test");
    });
  });

}).call(this);
