// Generated by CoffeeScript 1.9.3
(function() {
  var doRound;

  app.model.Src = new Maslosoft.Ko.BalinDev.Models.Src({
    filename: 'maslosoft.png'
  });

  ko.applyBindings({
    model: app.model
  });

  doRound = function() {
    var index, json, model, res, results;
    json = JSON.stringify(app.model);
    res = JSON.parse(json);
    results = [];
    for (index in res) {
      model = res[index];
      results.push(app.model[index] = ko.tracker.factory(res[index]));
    }
    return results;
  };

  describe('Test if will allow roundtrip of simple value, using new', function() {
    it('should not fail', function() {});
    return it('should have name', function() {
      assert.equal(app.model.Src.filename, 'maslosoft.png');
      doRound();
      return assert.equal(app.model.Src.filename, 'maslosoft.png');
    });
  });

}).call(this);
