// Generated by CoffeeScript 1.10.0
(function() {
  var test;

  test = function() {
    var doRound;
    balin.model.Src = new Maslosoft.Ko.BalinDev.Models.Src({
      filename: 'maslosoft.png'
    });
    ko.applyBindings({
      model: balin.model
    }, document.getElementById('ko-balin'));
    doRound = function() {
      var index, json, model, res, results;
      json = JSON.stringify(balin.model);
      res = JSON.parse(json);
      results = [];
      for (index in res) {
        model = res[index];
        results.push(balin.model[index] = ko.tracker.factory(res[index]));
      }
      return results;
    };
    return describe('Test if will allow roundtrip of simple value, using new', function() {
      return it('Should have same value after getting data from JSON', function() {
        assert.equal(balin.model.Src.filename, 'maslosoft.png');
        doRound();
        return assert.equal(balin.model.Src.filename, 'maslosoft.png');
      });
    });
  };

  setTimeout(test, 1000);

}).call(this);
