// Generated by CoffeeScript 1.9.3
(function() {
  if (!this.Maslosoft) {
    this.Maslosoft = {};
  }

  if (!this.Maslosoft.Ko.BalinDev) {
    this.Maslosoft.Ko.BalinDev = {};
  }

  this.Maslosoft.Ko.BalinDev.BogusValidator = (function() {
    function BogusValidator() {}

    return BogusValidator;

  })();

}).call(this);
