// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if (!this.Maslosoft) {
    this.Maslosoft = {};
  }

  if (!this.Maslosoft.Ko.BalinDev) {
    this.Maslosoft.Ko.BalinDev = {};
  }

  this.Maslosoft.Ko.BalinDev.EmailValidator = (function(superClass) {
    extend(EmailValidator, superClass);

    function EmailValidator() {
      return EmailValidator.__super__.constructor.apply(this, arguments);
    }

    EmailValidator.prototype.pattern = '^[a-z]+@[a-z]+\\.[a-z]+$';

    EmailValidator.prototype.allowEmpty = true;

    EmailValidator.prototype.isValid = function(value) {
      var regexp, valid;
      if (this.allowEmpty && !value) {
        return true;
      }
      if (value.match(/com/)) {
        console.log('warn...');
        this.addWarning("This domain freqently rejected our e-mail, please add admin@example.com to your whitelist");
      }
      regexp = new RegExp(this.pattern, this.flags);
      valid = regexp.test(value);
      if (!valid) {
        this.addError("Please enter valid e-mail");
      }
      return valid;
    };

    return EmailValidator;

  })(this.Maslosoft.Ko.Balin.BaseValidator);

}).call(this);
