// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if (!this.Maslosoft) {
    this.Maslosoft = {};
  }

  if (!this.Maslosoft.Ko.BalinDev) {
    this.Maslosoft.Ko.BalinDev = {};
  }

  this.Maslosoft.Ko.BalinDev.RegExpValidator = (function(superClass) {
    extend(RegExpValidator, superClass);

    function RegExpValidator() {
      return RegExpValidator.__super__.constructor.apply(this, arguments);
    }

    RegExpValidator.prototype.pattern = '';

    RegExpValidator.prototype.flags = '';

    RegExpValidator.prototype.getErrors = function() {
      return ["Should match " + this.pattern];
    };

    RegExpValidator.prototype.isValid = function(value) {
      var regexp;
      regexp = new RegExp(this.pattern, this.flags);
      return regexp.test(value);
    };

    return RegExpValidator;

  })(this.Maslosoft.Ko.Balin.BaseValidator);

}).call(this);
