// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if (!this.Maslosoft) {
    this.Maslosoft = {};
  }

  if (!this.Maslosoft.Ko.BalinDev) {
    this.Maslosoft.Ko.BalinDev = {};
  }

  this.Maslosoft.Ko.BalinDev.RequiredValidator = (function(superClass) {
    extend(RequiredValidator, superClass);

    function RequiredValidator() {
      return RequiredValidator.__super__.constructor.apply(this, arguments);
    }

    RequiredValidator.prototype.getErrors = function() {
      return ["This is required"];
    };

    RequiredValidator.prototype.isValid = function(value) {
      return !!value;
    };

    return RequiredValidator;

  })(this.Maslosoft.Ko.Balin.BaseValidator);

}).call(this);
