// Generated by CoffeeScript 1.9.3
(function() {
  if (!this.Maslosoft) {
    this.Maslosoft = {};
  }

  if (!this.Maslosoft.Ko.BalinDev) {
    this.Maslosoft.Ko.BalinDev = {};
  }

  this.Maslosoft.Ko.BalinDev.TitleRenderer = (function() {
    function TitleRenderer(tree, options) {}

    TitleRenderer.prototype.render = function(node, span) {
      var description;
      description = '';
      if (node.description) {
        description = "<em class='text-muted'>" + node.description + "</em>";
      }
      return span.html("<b>" + node.title + "</b> " + description + " (ID: " + node.id + ")");
    };

    return TitleRenderer;

  })();

}).call(this);
